alter table PAXBASE_OFFSHORE_USER add constraint FK_PAXBASE_OFFSHORE_USER_COMPANY foreign key (COMPANY_ID) references SYS_CATEGORY(ID);
create index IDX_PAXBASE_OFFSHORE_USER_COMPANY on PAXBASE_OFFSHORE_USER (COMPANY_ID);
