-- begin PAXBASE_COMPANY
create unique index IDX_PAXBASE_COMPANY_UNIQ_EMAIL on PAXBASE_COMPANY (EMAIL) ^
-- end PAXBASE_COMPANY
-- begin PAXBASE_TRANSFER
alter table PAXBASE_TRANSFER add constraint FK_PAXBASE_TRANSFER_CREW_CHANGE foreign key (CREW_CHANGE_ID) references PAXBASE_CREW_CHANGE(ID)^
alter table PAXBASE_TRANSFER add constraint FK_PAXBASE_TRANSFER_OPERATED_BY foreign key (OPERATED_BY_ID) references PAXBASE_COMPANY(ID)^
alter table PAXBASE_TRANSFER add constraint FK_PAXBASE_TRANSFER_MODE_OF_TRANSFER foreign key (MODE_OF_TRANSFER_ID) references PAXBASE_MODE_OF_TRANSFER(ID)^
create index IDX_PAXBASE_TRANSFER_CREW_CHANGE on PAXBASE_TRANSFER (CREW_CHANGE_ID)^
create index IDX_PAXBASE_TRANSFER_OPERATED_BY on PAXBASE_TRANSFER (OPERATED_BY_ID)^
create index IDX_PAXBASE_TRANSFER_MODE_OF_TRANSFER on PAXBASE_TRANSFER (MODE_OF_TRANSFER_ID)^
-- end PAXBASE_TRANSFER
-- begin PAXBASE_SITEalter table PAXBASE_SITE add constraint FK_PAXBASE_SITE_PARENT_SITE foreign key (PARENT_SITE_ID) references PAXBASE_SITE(ID)^
alter table PAXBASE_SITE add constraint FK_PAXBASE_SITE_SITE_TYPE foreign key (SITE_TYPE_ID) references PAXBASE_SITE_TYPE(ID)^
create index IDX_PAXBASE_SITE_PARENT_SITE on PAXBASE_SITE (PARENT_SITE_ID)^
create index IDX_PAXBASE_SITE_SITE_TYPE on PAXBASE_SITE (SITE_TYPE_ID)^
-- end PAXBASE_SITE
-- begin PAXBASE_WAYPOINT
alter table PAXBASE_WAYPOINT add constraint FK_PAXBASE_WAYPOINT_TRANSFER foreign key (TRANSFER_ID) references PAXBASE_TRANSFER(ID)^
alter table PAXBASE_WAYPOINT add constraint FK_PAXBASE_WAYPOINT_SITE foreign key (SITE_ID) references PAXBASE_SITE(ID)^
create index IDX_PAXBASE_WAYPOINT_TRANSFER on PAXBASE_WAYPOINT (TRANSFER_ID)^
create index IDX_PAXBASE_WAYPOINT_SITE on PAXBASE_WAYPOINT (SITE_ID)^
-- end PAXBASE_WAYPOINT
-- begin PAXBASE_PAYLOADalter table PAXBASE_PAYLOAD add constraint FK_PAXBASE_PAYLOAD_CRAFT_TYPE foreign key (CRAFT_TYPE_ID) references PAXBASE_CRAFT_TYPE(ID)^
alter table PAXBASE_PAYLOAD add constraint FK_PAXBASE_PAYLOAD_SITE_A foreign key (SITE_A_ID) references PAXBASE_SITE(ID)^
alter table PAXBASE_PAYLOAD add constraint FK_PAXBASE_PAYLOAD_SITE_B foreign key (SITE_B_ID) references PAXBASE_SITE(ID)^
create index IDX_PAXBASE_PAYLOAD_SITE_A on PAXBASE_PAYLOAD (SITE_A_ID)^
create index IDX_PAXBASE_PAYLOAD_SITE_B on PAXBASE_PAYLOAD (SITE_B_ID)^
create index IDX_PAXBASE_PAYLOAD_CRAFT_TYPE on PAXBASE_PAYLOAD (CRAFT_TYPE_ID)^
-- end PAXBASE_PAYLOAD
-- begin PAXBASE_DUTY_PERIODalter table PAXBASE_DUTY_PERIOD add constraint FK_PAXBASE_DUTY_PERIOD_PERSON_ON_DUTY foreign key (PERSON_ON_DUTY_ID) references SEC_USER(ID)^
alter table PAXBASE_DUTY_PERIOD add constraint FK_PAXBASE_DUTY_PERIOD_SITE foreign key (SITE_ID) references PAXBASE_SITE(ID)^
alter table PAXBASE_DUTY_PERIOD add constraint FK_PAXBASE_DUTY_PERIOD_CONTRACTOR foreign key (CONTRACTOR_ID) references PAXBASE_COMPANY(ID)^
alter table PAXBASE_DUTY_PERIOD add constraint FK_PAXBASE_DUTY_PERIOD_FUNCTION_CATEGORY foreign key (FUNCTION_CATEGORY_ID) references PAXBASE_FUNCTION_CATEGORY(ID)^
create index IDX_PAXBASE_DUTY_PERIOD_PERSON_ON_DUTY on PAXBASE_DUTY_PERIOD (PERSON_ON_DUTY_ID)^
create index IDX_PAXBASE_DUTY_PERIOD_SITE on PAXBASE_DUTY_PERIOD (SITE_ID)^
create index IDX_PAXBASE_DUTY_PERIOD_CONTRACTOR on PAXBASE_DUTY_PERIOD (CONTRACTOR_ID)^
create index IDX_PAXBASE_DUTY_PERIOD_FUNCTION_CATEGORY on PAXBASE_DUTY_PERIOD (FUNCTION_CATEGORY_ID)^
-- end PAXBASE_DUTY_PERIOD
-- begin SEC_USERalter table SEC_USER add constraint FK_SEC_USER_COMPANY foreign key (COMPANY_ID) references PAXBASE_COMPANY(ID)^
create index IDX_SEC_USER_COMPANY on SEC_USER (COMPANY_ID)^
alter table SEC_USER add constraint FK_SEC_USER_DEPARTMENT foreign key (DEPARTMENT_ID) references PAXBASE_DEPARTMENT(ID)^
create index IDX_SEC_USER_DEPARTMENT on SEC_USER (DEPARTMENT_ID)^
alter table SEC_USER add constraint FK_SEC_USER_COMPANY foreign key (COMPANY_ID) references PAXBASE_COMPANY(ID)^
create index IDX_SEC_USER_COMPANY on SEC_USER (COMPANY_ID)^
alter table SEC_USER add constraint FK_SEC_USER_DEPARTMENT foreign key (DEPARTMENT_ID) references PAXBASE_DEPARTMENT(ID)^
create index IDX_SEC_USER_DEPARTMENT on SEC_USER (DEPARTMENT_ID)^
-- end SEC_USER

-- begin PAXBASE_CAMPAIGN
alter table PAXBASE_CAMPAIGN add constraint FK_PAXBASE_CAMPAIGN_SITE foreign key (SITE_ID) references PAXBASE_SITE(ID)^
alter table PAXBASE_CAMPAIGN add constraint FK_PAXBASE_CAMPAIGN_FUNCTION_CATEGORY foreign key (FUNCTION_CATEGORY_ID) references PAXBASE_FUNCTION_CATEGORY(ID)^
create index IDX_PAXBASE_CAMPAIGN_SITE on PAXBASE_CAMPAIGN (SITE_ID)^
create index IDX_PAXBASE_CAMPAIGN_FUNCTION_CATEGORY on PAXBASE_CAMPAIGN (FUNCTION_CATEGORY_ID)^
-- end PAXBASE_CAMPAIGN

-- begin PAXBASE_PERIOD_TYPE
alter table PAXBASE_PERIOD_TYPE add constraint FK_PAXBASE_PERIOD_TYPE_PARENT_TYPE foreign key (PARENT_TYPE_ID) references PAXBASE_PERIOD_TYPE(ID)^
create index IDX_PAXBASE_PERIOD_TYPE_PARENT_TYPE on PAXBASE_PERIOD_TYPE (PARENT_TYPE_ID)^
-- end PAXBASE_PERIOD_TYPE

-- begin PAXBASE_FUNCTION_CATEGORY
alter table PAXBASE_FUNCTION_CATEGORY add constraint FK_PAXBASE_FUNCTION_CATEGORY_PARENT_TYPE foreign key (PARENT_TYPE_ID) references PAXBASE_FUNCTION_CATEGORY(ID)^
create index IDX_PAXBASE_FUNCTION_CATEGORY_PARENT_TYPE on PAXBASE_FUNCTION_CATEGORY (PARENT_TYPE_ID)^
-- end PAXBASE_FUNCTION_CATEGORY
-- begin PAXBASE_SITE_TYPE
alter table PAXBASE_SITE_TYPE add constraint FK_PAXBASE_SITE_TYPE_PARENT_TYPE foreign key (PARENT_TYPE_ID) references PAXBASE_SITE_TYPE(ID)^
create index IDX_PAXBASE_SITE_TYPE_PARENT_TYPE on PAXBASE_SITE_TYPE (PARENT_TYPE_ID)^
-- end PAXBASE_SITE_TYPE
-- begin PAXBASE_CONTRACTOR_DUTY_PERIOD
alter table PAXBASE_CONTRACTOR_DUTY_PERIOD add constraint FK_PAXBASE_CONTRACTOR_DUTY_PERIOD_CONTRACTOR foreign key (CONTRACTOR_ID) references PAXBASE_COMPANY(ID)^
alter table PAXBASE_CONTRACTOR_DUTY_PERIOD add constraint FK_PAXBASE_CONTRACTOR_DUTY_PERIOD_FUNCTION_CATEGORY foreign key (FUNCTION_CATEGORY_ID) references PAXBASE_FUNCTION_CATEGORY(ID)^
create index IDX_PAXBASE_CONTRACTOR_DUTY_PERIOD_CONTRACTOR on PAXBASE_CONTRACTOR_DUTY_PERIOD (CONTRACTOR_ID)^
create index IDX_PAXBASE_CONTRACTOR_DUTY_PERIOD_FUNCTION_CATEGORY on PAXBASE_CONTRACTOR_DUTY_PERIOD (FUNCTION_CATEGORY_ID)^
-- end PAXBASE_CONTRACTOR_DUTY_PERIOD

-- begin PAXBASE_CERTIFICATE
alter table PAXBASE_CERTIFICATE add constraint FK_PAXBASE_CERTIFICATE_VERFIED_BY foreign key (VERFIED_BY_ID) references SEC_USER(ID)^
alter table PAXBASE_CERTIFICATE add constraint FK_PAXBASE_CERTIFICATE_QUALIFICATION_TYPE foreign key (QUALIFICATION_TYPE_ID) references PAXBASE_QUALIFICATION_TYPE(ID)^
alter table PAXBASE_CERTIFICATE add constraint FK_PAXBASE_CERTIFICATE_OFFSHORE_USER foreign key (OFFSHORE_USER_ID) references SEC_USER(ID)^
alter table PAXBASE_CERTIFICATE add constraint FK_PAXBASE_CERTIFICATE_FILE_DATA foreign key (FILE_DATA_ID) references SYS_FILE(ID)^
alter table PAXBASE_CERTIFICATE add constraint FK_PAXBASE_CERTIFICATE_CERTIFICATE_TYPE foreign key (CERTIFICATE_TYPE_ID) references PAXBASE_QUALIFICATION_TYPE(ID)^
create index IDX_PAXBASE_CERTIFICATE_VERFIED_BY on PAXBASE_CERTIFICATE (VERFIED_BY_ID)^
create index IDX_PAXBASE_CERTIFICATE_QUALIFICATION_TYPE on PAXBASE_CERTIFICATE (QUALIFICATION_TYPE_ID)^
create index IDX_PAXBASE_CERTIFICATE_OFFSHORE_USER on PAXBASE_CERTIFICATE (OFFSHORE_USER_ID)^
create index IDX_PAXBASE_CERTIFICATE_FILE_DATA on PAXBASE_CERTIFICATE (FILE_DATA_ID)^
create index IDX_PAXBASE_CERTIFICATE_CERTIFICATE_TYPE on PAXBASE_CERTIFICATE (CERTIFICATE_TYPE_ID)^
-- end PAXBASE_CERTIFICATE
-- begin PAXBASE_FUNCTION_ROLE_LINK
alter table PAXBASE_FUNCTION_ROLE_LINK add constraint FK_PFRL_JOBFUNCTION foreign key (FUNCTION_ID) references PAXBASE_JOBFUNCTION(ID)^
alter table PAXBASE_FUNCTION_ROLE_LINK add constraint FK_PFRL_ROLE foreign key (ROLE_ID) references PAXBASE_ROLE(ID)^
-- end PAXBASE_FUNCTION_ROLE_LINK

-- begin PAXBASE_DEPARTMENT
alter table PAXBASE_DEPARTMENT add constraint FK_PAXBASE_DEPARTMENT_PARENT_DEPARTMENT foreign key (PARENT_DEPARTMENT_ID) references PAXBASE_DEPARTMENT(ID)^
alter table PAXBASE_DEPARTMENT add constraint FK_PAXBASE_DEPARTMENT_LEADER foreign key (LEADER_ID) references SEC_USER(ID)^
alter table PAXBASE_DEPARTMENT add constraint FK_PAXBASE_DEPARTMENT_DEPUTY_LEADER foreign key (DEPUTY_LEADER_ID) references SEC_USER(ID)^
create index IDX_PAXBASE_DEPARTMENT_PARENT_DEPARTMENT on PAXBASE_DEPARTMENT (PARENT_DEPARTMENT_ID)^
create index IDX_PAXBASE_DEPARTMENT_LEADER on PAXBASE_DEPARTMENT (LEADER_ID)^
create index IDX_PAXBASE_DEPARTMENT_DEPUTY_LEADER on PAXBASE_DEPARTMENT (DEPUTY_LEADER_ID)^
-- end PAXBASE_DEPARTMENT
-- begin PAXBASE_CRAFT_TYPE
alter table PAXBASE_CRAFT_TYPE add constraint FK_PAXBASE_CRAFT_TYPE_MODE_OF_TRANSFER foreign key (MODE_OF_TRANSFER_ID) references PAXBASE_MODE_OF_TRANSFER(ID)^
create index IDX_PAXBASE_CRAFT_TYPE_MODE_OF_TRANSFER on PAXBASE_CRAFT_TYPE (MODE_OF_TRANSFER_ID)^
-- end PAXBASE_CRAFT_TYPE
-- begin PAXBASE_DUTY_PERIOD_TEMPLATE
alter table PAXBASE_DUTY_PERIOD_TEMPLATE add constraint FK_PAXBASE_DUTY_PERIOD_TEMPLATE_FUNCTION_CATEGORY foreign key (FUNCTION_CATEGORY_ID) references PAXBASE_FUNCTION_CATEGORY(ID)^
alter table PAXBASE_DUTY_PERIOD_TEMPLATE add constraint FK_PAXBASE_DUTY_PERIOD_TEMPLATE_SITE foreign key (SITE_ID) references PAXBASE_SITE(ID)^
alter table PAXBASE_DUTY_PERIOD_TEMPLATE add constraint FK_PAXBASE_DUTY_PERIOD_TEMPLATE_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_PAXBASE_DUTY_PERIOD_TEMPLATE_FUNCTION_CATEGORY on PAXBASE_DUTY_PERIOD_TEMPLATE (FUNCTION_CATEGORY_ID)^
create index IDX_PAXBASE_DUTY_PERIOD_TEMPLATE_SITE on PAXBASE_DUTY_PERIOD_TEMPLATE (SITE_ID)^
create index IDX_PAXBASE_DUTY_PERIOD_TEMPLATE_USER on PAXBASE_DUTY_PERIOD_TEMPLATE (USER_ID)^
-- end PAXBASE_DUTY_PERIOD_TEMPLATE
-- begin PAXBASE_ROLE_QUALIFICATION_TYPE
alter table PAXBASE_ROLE_QUALIFICATION_TYPE add constraint FK_PAXBASE_ROLE_QUALIFICATION_TYPE_QUALIFICATION_TYPE foreign key (QUALIFICATION_TYPE_ID) references PAXBASE_QUALIFICATION_TYPE(ID)^
alter table PAXBASE_ROLE_QUALIFICATION_TYPE add constraint FK_PAXBASE_ROLE_QUALIFICATION_TYPE_ROLE foreign key (ROLE_ID) references PAXBASE_ROLE(ID)^
create index IDX_PAXBASE_ROLE_QUALIFICATION_TYPE_QUALIFICATION_TYPE on PAXBASE_ROLE_QUALIFICATION_TYPE (QUALIFICATION_TYPE_ID)^
create index IDX_PAXBASE_ROLE_QUALIFICATION_TYPE_ROLE on PAXBASE_ROLE_QUALIFICATION_TYPE (ROLE_ID)^
-- end PAXBASE_ROLE_QUALIFICATION_TYPE
