-- begin SAAS_COMPANY
create unique index IDX_SAAS_COMPANY_UNIQ_EMAIL on SAAS_COMPANY (EMAIL) ^
-- end SAAS_COMPANY
-- begin SAAS_TRANSFER
alter table SAAS_TRANSFER add constraint FK_SAAS_TRANSFER_CREW_CHANGE foreign key (CREW_CHANGE_ID) references SAAS_CREW_CHANGE(ID)^
alter table SAAS_TRANSFER add constraint FK_SAAS_TRANSFER_OPERATED_BY foreign key (OPERATED_BY_ID) references SAAS_COMPANY(ID)^
create index IDX_SAAS_TRANSFER_OPERATED_BY on SAAS_TRANSFER (OPERATED_BY_ID)^
create index IDX_SAAS_TRANSFER_CREW_CHANGE on SAAS_TRANSFER (CREW_CHANGE_ID)^
-- end SAAS_TRANSFER
-- begin SAAS_SITE
alter table SAAS_SITE add constraint FK_SAAS_SITE_PARENT_SITE foreign key (PARENT_SITE_ID) references SAAS_SITE(ID)^
create unique index IDX_SAAS_SITE_UNIQ_NAME on SAAS_SITE (NAME) ^
create index IDX_SAAS_SITE_PARENT_SITE on SAAS_SITE (PARENT_SITE_ID)^
-- end SAAS_SITE
-- begin SAAS_WAYPOINT
alter table SAAS_WAYPOINT add constraint FK_SAAS_WAYPOINT_PREV_WAYPOINT foreign key (PREV_WAYPOINT_ID) references SAAS_WAYPOINT(ID)^
alter table SAAS_WAYPOINT add constraint FK_SAAS_WAYPOINT_NEXT_WAYPOINT foreign key (NEXT_WAYPOINT_ID) references SAAS_WAYPOINT(ID)^
alter table SAAS_WAYPOINT add constraint FK_SAAS_WAYPOINT_TRANSFER foreign key (TRANSFER_ID) references SAAS_TRANSFER(ID)^
alter table SAAS_WAYPOINT add constraint FK_SAAS_WAYPOINT_SITE foreign key (SITE_ID) references SAAS_SITE(ID)^
create index IDX_SAAS_WAYPOINT_SITE on SAAS_WAYPOINT (SITE_ID)^
create index IDX_SAAS_WAYPOINT_TRANSFER on SAAS_WAYPOINT (TRANSFER_ID)^
-- end SAAS_WAYPOINT
-- begin SAAS_OFFSHORE_USER
alter table SAAS_OFFSHORE_USER add constraint FK_SAAS_OFFSHORE_USER_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SAAS_OFFSHORE_USER_USER on SAAS_OFFSHORE_USER (USER_ID)^
-- end SAAS_OFFSHORE_USER
