alter table PAXBASE_CAMPAIGN add constraint FK_PAXBASE_CAMPAIGN_CATEGORY foreign key (CATEGORY_ID) references PAXBASE_FUNCTION_CATEGORY(ID);
create index IDX_PAXBASE_CAMPAIGN_CATEGORY on PAXBASE_CAMPAIGN (CATEGORY_ID);
