alter table PAXBASE_PERIOD_TYPE add constraint FK_PAXBASE_PERIOD_TYPE_PARENT_TYPE foreign key (PARENT_TYPE_ID) references PAXBASE_PERIOD_TYPE(ID);
create index IDX_PAXBASE_PERIOD_TYPE_PARENT_TYPE on PAXBASE_PERIOD_TYPE (PARENT_TYPE_ID);
