alter table PAXBASE_DUTY_PERIOD add constraint FK_PAXBASE_DUTY_PERIOD_CATEGORY foreign key (CATEGORY_ID) references PAXBASE_FUNCTION_CATEGORY(ID);
create index IDX_PAXBASE_DUTY_PERIOD_CATEGORY on PAXBASE_DUTY_PERIOD (CATEGORY_ID);
