alter table PAXBASE_DUTY_PERIOD add constraint FK_PAXBASE_DUTY_PERIOD_TYPE foreign key (TYPE_ID) references PAXBASE_PERIOD_TYPE(ID);
create index IDX_PAXBASE_DUTY_PERIOD_TYPE on PAXBASE_DUTY_PERIOD (TYPE_ID);
