alter table PAXBASE_SERVICE_PERIOD add constraint FK_PAXBASE_SERVICE_PERIOD_OFFSHORE_USER foreign key (OFFSHORE_USER_ID) references SEC_USER(ID);
alter table PAXBASE_SERVICE_PERIOD add constraint FK_PAXBASE_SERVICE_PERIOD_TYPE foreign key (TYPE_ID) references PAXBASE_PERIOD_TYPE(ID);
create index IDX_PAXBASE_SERVICE_PERIOD_TYPE on PAXBASE_SERVICE_PERIOD (TYPE_ID);
create index IDX_PAXBASE_SERVICE_PERIOD_OFFSHORE_USER on PAXBASE_SERVICE_PERIOD (OFFSHORE_USER_ID);
