alter table PAXBASE_SERVICE_PERIOD add constraint FK_PAXBASE_SERVICE_PERIOD_SITE foreign key (SITE_ID) references PAXBASE_SITE(ID);
create index IDX_PAXBASE_SERVICE_PERIOD_SITE on PAXBASE_SERVICE_PERIOD (SITE_ID);
