alter table PAXBASE_SITE_TYPE add constraint FK_PAXBASE_SITE_TYPE_PARENT_TYPE foreign key (PARENT_TYPE_ID) references PAXBASE_SITE_TYPE(ID);
create index IDX_PAXBASE_SITE_TYPE_PARENT_TYPE on PAXBASE_SITE_TYPE (PARENT_TYPE_ID);
