alter table PAXBASE_ROLE_QUALIFICATION_TYPE_LINK add constraint FK_PRQTL_ROLE foreign key (ROLE_ID) references PAXBASE_ROLE(ID);
alter table PAXBASE_ROLE_QUALIFICATION_TYPE_LINK add constraint FK_PRQTL_QUALIFICATION_TYPE foreign key (QUALIFICATION_TYPE_ID) references PAXBASE_QUALIFICATION_TYPE(ID);
