alter table PAXBASE_SITE_ROLE_RULE add constraint FK_PAXBASE_SITE_ROLE_RULE_SITE foreign key (SITE_ID) references PAXBASE_SITE(ID);
create index IDX_PAXBASE_SITE_ROLE_RULE_SITE on PAXBASE_SITE_ROLE_RULE (SITE_ID);
