alter table PAXBASE_DUTY_PERIOD add constraint FK_PAXBASE_DUTY_PERIOD_PERSON_ON_DUTY foreign key (PERSON_ON_DUTY_ID) references PAXBASE_APP_USER(ID);
create index IDX_PAXBASE_DUTY_PERIOD_PERSON_ON_DUTY on PAXBASE_DUTY_PERIOD (PERSON_ON_DUTY_ID);
