alter table PAXBASE_SITE_ROLE_RULES add constraint FK_PAXBASE_SITE_ROLE_RULES_SITE foreign key (SITE_ID) references PAXBASE_SITE(ID);
create index IDX_PAXBASE_SITE_ROLE_RULES_SITE on PAXBASE_SITE_ROLE_RULES (SITE_ID);
