alter table PAXBASE_DEPARTMENT add constraint FK_PAXBASE_DEPARTMENT_DEPUTY_LEADER foreign key (DEPUTY_LEADER_ID) references PAXBASE_APP_USER(ID);
create index IDX_PAXBASE_DEPARTMENT_DEPUTY_LEADER on PAXBASE_DEPARTMENT (DEPUTY_LEADER_ID);
