alter table PAXBASE_DEPARTMENT add constraint FK_PAXBASE_DEPARTMENT_LEADER foreign key (LEADER_ID) references PAXBASE_APP_USER(ID);
create index IDX_PAXBASE_DEPARTMENT_LEADER on PAXBASE_DEPARTMENT (LEADER_ID);
