alter table PAXBASE_CERTIFICATE add constraint FK_PAXBASE_CERTIFICATE_OFFSHORE_USER foreign key (OFFSHORE_USER_ID) references PAXBASE_APP_USER(ID);
create index IDX_PAXBASE_CERTIFICATE_OFFSHORE_USER on PAXBASE_CERTIFICATE (OFFSHORE_USER_ID);
