alter table PAXBASE_SITE_ROLE_RULES_ROLE_LINK add constraint FK_SITROLRULROL_SITE_ROLE_RULES foreign key (SITE_ROLE_RULES_ID) references PAXBASE_SITE_ROLE_RULES(ID);
alter table PAXBASE_SITE_ROLE_RULES_ROLE_LINK add constraint FK_SITROLRULROL_ROLE foreign key (ROLE_ID) references PAXBASE_ROLE(ID);
